version: "3.9"

services:
  edge-proxy:
    build:
      context: .
      dockerfile: dockerfile
    container_name: edge-proxy
    networks:
      - proxy_network
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - certs:/app/certs
      - ./config.yml:/app/config.yml:Z

volumes:
  certs:

networks:
  proxy_network:
    external: true
