http:
  address: ":80"
  redirect_to_https: true

https:
  address: ":443"

tls:
  cache_dir: /app/certs
  domains:
    - zelchi.com
    - pesquisa.zelchi.com
    - envolve.zelchi.com

routes:
  - host: zelchi.com
    upstream: http://zelchi-blog:3001

  - host: pesquisa.zelchi.com
    upstream: http://pesquisa-hardware:3002

  - host: envolve.zelchi.com
    upstream: http://envolve-dev:3003
